http:
  port: 8005

admin:
  port: 9876
  host: localhost

logLevel: debug # Ensure this is at the root level

apiEndpoints:
  userApi:
    host: localhost
    paths: ["/api/users/*", "/api/users"]

serviceEndpoints:
  userService:
    url: "http://localhost:3001"

policies:
  - cors
  - proxy

pipelines:
  default:
    apiEndpoints:
      - userApi
    policies:
      - cors:
          action:
            origin: ["http://localhost:4200"]
            methods:
              - HEAD
              - PUT
              - POST
              - DELETE
              - PATCH
            credentials: true
            headers: ["Authorization", "Content-Type", "Accept"]
            exposeHeaders: ["Authorization", "Content-Type"]


      - proxy:
          - action:
              serviceEndpoint: userService
